# fly.toml app configuration file generated for frontend-nanodegree-resume on 2024-12-13T19:17:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-nanodegree-resume'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
